### ISSUE TITLE
Fails to link with a custom install prefix.

### ISSUE THREAD

**Issue by drmpeg** [igorauad/gr-dvbs2rx#1]
The correct way to link with gr_filter is as follows:

1) In the top level CMakeLists,txt, add the line:

```find_package(Gnuradio COMPONENTS fft filter blocks)```

after the line:

```find_package(Gnuradio "3.9.2" REQUIRED)```

2) In lib/CMakeLists.txt, change ```gnuradio-filter``` to ```gnuradio::gnuradio-filter```

**Comment by marcusmueller** [comment]
fix in #4
