### ISSUE TITLE
CUDA Compatibity

### ISSUE THREAD

**Issue by sumanthraikar** [igorauad/gr-dvbs2rx#21]
Hi, regarding getting a DVBS2 signal at a symbol rate of 30MSPS. Assuming your design blocks were CUDA optimized for jetson Tx2. Do you think your design would work for receiving a wide bandwidth signal?

**Comment by igorauad** [comment]
HI @sumanthraikar ,

I'm afraid I don't have a well-defined way to estimate whether a particular symbol rate would work with a specific CPU or GPU (if we were to have GPU implementation). There are so many factors involved that it becomes tough to come up with something like that. For instance, we depend on the following:
- The GNU Radio scheduler copying/moving samples between blocks and their buffers.
- The operating SNR, which affects how much FEC decoding activity there is.
- The other processes using the CPU and memory on the operating system.

Of course, we could assume some conditions to analyze the problem, like CPU free of processes and SNR with little margin and max LDPC iterations. However, I haven't gone through this exercise. I'd certainly be interested in such an analysis if you were to pursue it.

Off the top of my head, I can tell you there are a few Rx parameters to somewhat tune the computational burden: the matched RRC filter length (controlled by parameter `--rrc-delay`), the periodicity of coarse frequency offset estimation (parameter `--pl-freq-est-period`), and the max number of LPDC iterations (`--ldpc-iterations`). However, keep in mind these parameters also affect the decoding performance, so the CPU speed gains are not free. They are tuned based on a tradeoff between decoding and CPU performance.

Thanks
