### ISSUE TITLE
Option to switch between multiple video channels (as in a regular TV)

### ISSUE THREAD

**Issue by sumanthraikar** [igorauad/gr-dvbs2rx#25]
I think data (ts packets) from multiple telecasters ((like news, sports channels, etc..) on a single satellite is broadcasted all at once. In regular TV, we have the option to switch between various telecasters. But I don't understand how to switch in the case of GNU Radio design. 
Sorry if this was a very basic lack of understanding on my part.

I also want to know what changes could help dvbs2-rx work with a higher sampling rate, like 30MSPS on CPU/GPU. Would it allow a higher sampling rate if I use Jetson TX2 GPU and implement decoders and synchronization? 
If this is not possible, do you suggest an FPGA implementation?

**Comment by igorauad** [comment]
@sumanthraikar I'm cleaning up some issues that have been pending in the repo for a long time. 

I'm sorry for not replying to this before. If you are still interested, or for others reading this, please check out my GRCon22 talk, where I discuss some performance bottlenecks. Specifically, see the CPU utilization section: https://www.youtube.com/watch?v=qcqvfElQUVk&t=580s.

Thanks
