### ISSUE TITLE
Error Using PlutoSDR Transmit

### ISSUE THREAD

**Issue by MalinkyZubr** [igorauad/gr-dvbs2rx#41]
Hi. I am following the usage guide at https://igorauad.github.io/gr-dvbs2rx/docs/usage.html attempting to transmit using my plutoSDR unit. Running `tsp -I craft --pid 100 | dvbs2-tx --sink plutosdr --freq 1316.9e6 --sym-rate 1e6` results in the following error:
```
File "/usr/local/bin/dvbs2-rx", line 1631, in <module>
    main()
  File "/usr/local/bin/dvbs2-rx", line 1587, in main
    tb = DVBS2RxTopBlock(options)
  File "/usr/local/bin/dvbs2-rx", line 156, in __init__
    source_block = self.connect_source()
  File "/usr/local/bin/dvbs2-rx", line 755, in connect_source
    source = self.setup_plutosdr_source()
  File "/usr/local/bin/dvbs2-rx", line 665, in setup_plutosdr_source
    iio_pluto_source.set_samplerate(self.samp_rate)
TypeError: set_samplerate(): incompatible function arguments. The following argument types are supported:
    1. (self: gnuradio.iio.iio_python.fmcomms2_source_fc32, samplerate: int) -> None

Invoked with: <gnuradio.iio.iio_python.fmcomms2_source_fc32 object at 0x7133035c1170>, 2000000.0
```

all prior test commands work well. I tried using both the docker image and on my local system. 

Seems like very neat and convenient software. I look forward to getting it working. Thanks!

**Comment by igorauad** [comment]
@MalinkyZubr Thanks for your interest in the project. This is the same issue as the one reported in https://github.com/igorauad/gr-dvbs2rx/issues/38. I've just pushed a fix in 130c315.
